### ISSUE TITLE
[BUG] Live Preview is removed

### ISSUE THREAD

**Issue by Mara-Li** [chrisgrieser/obsidian-theme-design-utilities#2]
**Describe the Bug**
After using the plugin to saw some things on mobile, I saw that *live preview* was disabled. 

**To Reproduce**
1. Start the plugin in mobile mode
2. Return to normal mode

**Checklist**
- [x] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
So sorry I am only replying to this now – somehow I think I have forgotten to reply to it. 🙏 

---

what do you mean by "removed"? 🤔 

Could also be some issue since at the time of your posting, live preview was still an insider release feature, so could you check whether the issue still occurs with the current release?

**Comment by Mara-Li** [comment]
I close the issue : It now work as a charm. Thank you for this amazing plugin ! I debug my mobile css snippet with it <3.

**Comment by chrisgrieser** [comment]
love it when problems solve themselves 😄 

Thanks!
